// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxrylemdyrzmmlzfrknw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4cnlsZW1keXJ6bW1semZya253Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDIzMjcsImV4cCI6MjA2MTQxODMyN30.yioLydaOqB3JuzYeYZVqAnfZmLA2o3Ui5RxpWrD79pU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);